/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Dealer, Shop, Product, Order, Expense, Investment } from './types';

// Initial pre-loaded data for realistic Bangladesh-focused company setup
export const INITIAL_DEALERS: Dealer[] = [];

export const INITIAL_SHOPS: Shop[] = [];

export const INITIAL_PRODUCTS: Product[] = [];

export const INITIAL_ORDERS: Order[] = [];

export const INITIAL_EXPENSES: Expense[] = [];

export const INITIAL_INVESTMENTS: Investment[] = [];

// Translations dictionary
export const translations = {
  en: {
    appName: "Company & Dealer Management System",
    welcome: "Welcome",
    loginAs: "Login Profile / Switch View:",
    adminOwner: "Admin & Owner",
    dealer: "Dealer",
    language: "Language",
    dashboard: "Dashboard",
    dealers: "Dealers",
    shops: "Shops",
    products: "Products",
    orders: "Orders",
    expenses: "Expenses",
    investments: "Investments",
    financials: "Financial Overview",
    totalInvestments: "Total Investment",
    totalRevenue: "Total Revenue (Sales)",
    totalExpenses: "Total Expenses",
    netProfit: "Net Profit",
    profitFromOrders: "Profit from Orders",
    pendingOrdersCount: "Pending Orders",
    activeDealersCount: "Active Dealers",
    totalShopsCount: "Registered Shops",
    totalProductsCount: "Total Products",
    addDealer: "Add New Dealer",
    addShop: "Add New Shop",
    addProduct: "Add New Product",
    addOrder: "Create New Order",
    addExpense: "Record New Expense",
    addInvestment: "Record New Investment",
    name: "Name",
    phone: "Phone",
    email: "Email",
    area: "Area/Region",
    ownerName: "Owner Name",
    address: "Address",
    selectDealer: "Select Dealer",
    sku: "SKU / Code",
    costPrice: "Cost Price (Company Buying)",
    sellingPrice: "Selling Price (Selling to Shop)",
    stock: "Stock Quantity",
    unit: "Unit",
    category: "Category",
    amount: "Amount (BDT)",
    date: "Date",
    description: "Description",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    confirmDelete: "Are you sure you want to delete this?",
    status: "Status",
    items: "Items",
    total: "Total",
    pending: "Pending",
    ready: "Ready for Delivery",
    delivered: "Delivered",
    cancelled: "Cancelled",
    orderDate: "Order Date",
    profit: "Profit",
    subtotal: "Subtotal",
    selectShop: "Select Shop",
    selectProduct: "Select Product",
    quantity: "Quantity",
    addItem: "Add Product Item",
    orderPlacedSuccess: "Order placed successfully!",
    stockRemaining: "Stock remaining",
    allDealers: "All Dealers",
    allShops: "All Retail Shops",
    allProducts: "Company Products Catalog",
    allOrders: "Orders Ledger",
    allExpenses: "Business Expenses Ledger",
    allInvestments: "Capital Investment Ledger",
    costOfGoodsSold: "Cost of Goods Sold (COGS)",
    grossProfit: "Gross Profit",
    noData: "No entries found.",
    searchPlaceholder: "Search here...",
    adminAccessOnly: "Administrative control only. View financial data and control all configurations.",
    dealerAccessOnly: "Dealer panel. Manage your designated shops and log client orders on the fly.",
    markAsDelivered: "Mark as Delivered",
    markAsCancelled: "Cancel Order",
    bdt: "৳",
    companyCapital: "Company Financial Health",
    addSuccess: "Successfully Added!",
    deleteSuccess: "Successfully Deleted!",
    updateSuccess: "Successfully Updated!",
    insufficientStock: "Insufficient stock available!",
    selectAtLeastOneItem: "Please select at least one product item with quantity > 0",
    fillAllFields: "Please fill out all required fields",
  },
  bn: {
    appName: "কোম্পানি ও ডিলার ম্যানেজমেন্ট সিস্টেম",
    welcome: "স্বাগতম",
    loginAs: "লগইন প্রোফাইল / ভিউ পরিবর্তন করুন:",
    adminOwner: "অ্যাডমিন ও ওনার (মালিক)",
    dealer: "ডিলার (Dealer)",
    language: "ভাষা",
    dashboard: "ড্যাশবোর্ড",
    dealers: "ডিলার তালিকা",
    shops: "দোকান তালিকা",
    products: "পণ্য তালিকা",
    orders: "অর্ডারসমূহ",
    expenses: "অন্যান্য খরচ",
    investments: "মোট ইনভেস্ট (বিনিয়োগ)",
    financials: "আর্থিক হিসাব-নিকাশ",
    totalInvestments: "মোট ইনভেস্টমেন্ট",
    totalRevenue: "মোট বিক্রয় (রেভিনিউ)",
    totalExpenses: "মোট অন্যান্য খরচ",
    netProfit: "নিট লাভ (Net Profit)",
    profitFromOrders: "অর্ডার থেকে অর্জিত লাভ",
    pendingOrdersCount: "অপেক্ষমান অর্ডার",
    activeDealersCount: "সক্রিয় ডিলার",
    totalShopsCount: "নিবন্ধিত দোকান",
    totalProductsCount: "মোট পণ্য ধরণ",
    addDealer: "নতুন ডিলার যুক্ত করুন",
    addShop: "নতুন দোকান যুক্ত করুন",
    addProduct: "নতুন পণ্য যুক্ত করুন",
    addOrder: "নতুন অর্ডার তৈরি করুন",
    addExpense: "নতুন খরচ লিপিবদ্ধ করুন",
    addInvestment: "নতুন ইনভেস্টমেন্ট লিপিবদ্ধ করুন",
    name: "নাম",
    phone: "মোবাইল নম্বর",
    email: "ইমেইল",
    area: "এলাকা/অঞ্চল",
    ownerName: "দোকানদারের নাম",
    address: "ঠিকানা",
    selectDealer: "ডিলার নির্বাচন করুন",
    sku: "এসকিউ / কোড",
    costPrice: "ক্রয়মূল্য (কোম্পানি ক্রয়)",
    sellingPrice: "বিক্রয়মূল্য (দোকানদারের জন্য)",
    stock: "স্টক পরিমাণ",
    unit: "ইউনিট / একক",
    category: "খরচের খাত",
    amount: "টাকার পরিমাণ (টাকা)",
    date: "তারিখ",
    description: "বিবরণ",
    actions: "অ্যাকশন",
    edit: "সম্পাদনা",
    delete: "মুছে ফেলুন",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    confirmDelete: "আপনি কি নিশ্চিত যে এটি মুছে ফেলতে চান?",
    status: "অবস্থা",
    items: "পণ্যসমূহ",
    total: "সর্বমোট",
    pending: "অপেক্ষমান",
    ready: "ডেলিভারির জন্য প্রস্তুত",
    delivered: "ডেলিভারি সম্পন্ন",
    cancelled: "বাতিলকৃত",
    orderDate: "অর্ডারের তারিখ",
    profit: "লাভ (প্রফিট)",
    subtotal: "উপ-মোট",
    selectShop: "দোকান নির্বাচন করুন",
    selectProduct: "পণ্য নির্বাচন করুন",
    quantity: "পরিমাণ",
    addItem: "পণ্য যুক্ত করুন",
    orderPlacedSuccess: "অর্ডারটি সফলভাবে গ্রহণ করা হয়েছে!",
    stockRemaining: "স্টক অবশিষ্ট আছে",
    allDealers: "সকল ডিলার",
    allShops: "সকল খুচরা দোকান",
    allProducts: "কোম্পানি পণ্য ক্যাটালগ",
    allOrders: "অর্ডার লেজার",
    allExpenses: "ব্যবসায়িক খরচ হিসাব",
    allInvestments: "মূলধন বিনিয়োগ লেজার",
    costOfGoodsSold: "বিক্রীত পণ্যের উৎপাদন ব্যয়",
    grossProfit: "মোট লাভ",
    noData: "কোন তথ্য পাওয়া যায়নি।",
    searchPlaceholder: "এখানে খুঁজুন...",
    adminAccessOnly: "প্রশাসনিক নিয়ন্ত্রণ প্যানেল। লাভ-লোকসান, ইনভেস্টমেন্ট ও ডিলার সম্পর্কিত সব হিসাব দেখুন ও নিয়ন্ত্রণ করুন।",
    dealerAccessOnly: "ডিলার প্যানেল। আপনার আন্ডারে থাকা খুচরা দোকানসমূহ পরিচালনা করুন এবং পণ্য অর্ডার বুক করুন।",
    markAsDelivered: "ডেলিভারি সম্পন্ন চিহ্নিত করুন",
    markAsCancelled: "অর্ডার বাতিল করুন",
    bdt: "৳",
    companyCapital: "কোম্পানি আর্থিক অবস্থা",
    addSuccess: "সফলভাবে যুক্ত করা হয়েছে!",
    deleteSuccess: "সফলভাবে মুছে ফেলা হয়েছে!",
    updateSuccess: "সফলভাবে আপডেট করা হয়েছে!",
    insufficientStock: "পর্যাপ্ত স্টক নেই!",
    selectAtLeastOneItem: "অনুগ্রহ করে কমপক্ষে ১টি পণ্য পরিমাণসহ নির্বাচন করুন",
    fillAllFields: "অনুগ্রহ করে সব প্রয়োজনীয় তথ্য পূরণ করুন",
  }
};
